In [2]:
# command mode: blue mode
# edit mode: green mode
# command mode -> edit mode : Press Enter or you can click using mouse in the cell
# edit mode -> command mode : Press Esc

# Ctrl + Enter : can used to run or execute the whole chunk of code you have written in the cell
# You will see a change in [] when you execute any cell
# Ctrl + Enter can execute the code but it will not add or move to the next cell.

#while
# Shift + Enter : Execute the code and move to next cell

In [1]:
print("Hello World")

Hello World

In [2]:
# add any cell above this cell, you can use 'a' only when you are in command mode
# add any cell bellow this cell, you can use 'b' only when you are in command mode
# dd can be used to delete a cell only in command mode

In [4]:
import pandas as pd
df = pd.read_csv("customers-100.csv")
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,72e8E9e4463C89A,Ellen,Bush,Christian-Patterson,Clementsland,Cape Verde,665-274-9635,675-916-4120x42795,sanchezkaitlyn@mann-fisher.org,2020-11-06,http://daniel.com/
1,2,03B8a96750a3DB6,Madeline,Mcfarland,Schaefer LLC,Gregoryfort,Sweden,001-981-200-8019,707.632.9351,zbarnett@mathis.com,2021-10-02,https://www.walker.com/
2,3,A88cFF67cfb657b,Jack,Pittman,Le-Velazquez,North Colinshire,Bosnia and Herzegovina,(343)295-0482,963-844-4387,pettygeorge@novak-wolf.com,2021-04-20,http://www.kline.com/
3,4,689cFdc5DfDa5aB,Meredith,Mckee,Pollard LLC,Dyershire,Oman,(776)510-1203,706.952.8037,jweaver@finley-faulkner.com,2021-02-19,http://obrien.biz/
4,5,bA42d9F3fcF2f80,Angela,Bradshaw,Gallagher-Conley,Annabury,North Macedonia,001-745-613-7845x668,449.816.8470,diamondcooke@friedman.com,2023-02-24,http://haynes-benjamin.com/